Repository mia-platform/console-sdk, pull requests merged in 2024-03, with the labels that each got.

#52 docs: update contributing with tag creation guidelines
  CONTRIBUTING.md
Labels: documentation

#53 feat: added configurationManagement rule fields to project schema
  README.md
  packages/console-types/CHANGELOG.md
  packages/console-types/src/types/project.test.ts
  packages/console-types/src/types/project.ts
  packages/console-types/src/types/tenant.ts
Labels: enhancement, types

#57 update: deps
  packages/console-types/CHANGELOG.md
  packages/console-types/src/types/tenant.test.ts
  packages/console-types/src/types/tenant.ts
Labels: enhancement

#59 Feat/IDP-435 webhooks constants
  packages/console-types/src/constants/index.ts
  packages/console-types/src/types/template.test.ts
  packages/console-types/src/types/template.ts
Labels: enhancement

#61 fix: fixed environments variables type
  packages/console-types/CHANGELOG.md
  packages/console-types/src/types/project.ts
Labels: enhancement
