Repository mia-platform/console-sdk, pull requests merged in 2024-06, with the labels that each got.

#135 fix: remove ssh url pattern
  packages/console-types/src/strings/en.json
  packages/console-types/src/strings/it.json
  packages/console-types/src/types/services.test.ts
  packages/console-types/src/types/services.ts
  packages/console-types/tap-snapshots/src/types/config.test.ts.test.cjs
  pnpm-lock.yaml
Labels: enhancement, types

#140 feat: add MongoDB view default routes
  .changeset/chilled-tomatoes-sip.md
  packages/console-types/src/constants/endpoints.ts
Labels: enhancement

#150 feat: Service environment variables from ConfigMap
  .changeset/sweet-mice-march.md
  packages/console-types/src/constants/services.ts
  packages/console-types/src/types/services.test.ts
  packages/console-types/src/types/services.ts
  packages/console-types/tap-snapshots/src/types/config.test.ts.test.cjs
Labels: enhancement

#152 Fix: lockfile
  .github/workflows/publish.yml
Labels: bug

#153 feat: export type EnvironmentVariablesFromConfigMap
  .changeset/good-fans-argue.md
  packages/console-types/src/index.ts
Labels: bug
